# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    'name': 'Custom HR Access Right',
    "version": "15.0.1.1.1",
    'category': 'Custom Access Right',
    'summary': 'Custom For Access Right',
    'description': """
       """,
    # 'website': '',
    'depends': [
        'big_module',
        'om_hr_payroll',
    ],
    'images': [
    ],
    'data': [
        'data/ir_cron.xml',
        'security/res_groups_crud_module_files.xml',
        'security/res_groups_crud_module_contact.xml',
        'security/res_groups_crud_module_improvement.xml',
        'security/res_groups_crud_module_perform_appraisal.xml',
        'security/res_groups_crud_module_overtime.xml',
        'security/res_groups_crud_module_booth.xml',
        'security/res_groups_crud_module_elearning.xml',
        'security/res_groups_crud_module_surveys.xml',
        'security/res_groups_crud_module_employee.xml',
        'security/res_groups_crud_module_payroll.xml',
        'security/res_groups_crud_module_attendance.xml',
        'security/res_groups_crud_module_recruitment.xml',
        'security/res_groups_crud_module_timeoff.xml',
        'security/ir_rule.xml',
        'views/documents_files.xml',
        'views/documents_directories.xml',
        'views/documents_configuration.xml',
        'views/contacts_contacts.xml',
        'views/contacts_configuration.xml',
        'views/improvement_improvement.xml',
        'views/improvement_suggestion.xml',
        'views/improvement_report_configuration.xml',
        'views/perfomance_form_a.xml',
        'views/perfomance_form_b.xml',
        'views/perfomance_report_configuration.xml',
        'views/overtime_overtime.xml',
        'views/meeting_booth.xml',
        'views/meeting_master_booth.xml',
        'views/elaerning_courses.xml',
        'views/elaerning_content.xml',
        'views/elaerning_reviews.xml',
        'views/elaerning_certification.xml',
        'views/elearning_report_configuration.xml',
        'views/surveys_questions.xml',
        'views/surveys_suggested_values.xml',
        'views/surveys_participations.xml',
        'views/surveys_detailed_answer.xml',
        'views/surveys_report.xml',
        'views/employee_employee.xml',
        'views/employee_perjalanan_dinas.xml',
        'views/employee_fpsk.xml',
        'views/employee_pkwt.xml',
        'views/employee_terminasi.xml',
        'views/employee_jenis_terminasi.xml',
        'views/employee_department.xml',
        'views/payroll_payslip.xml',
        'views/payroll_batches.xml',
        'views/payroll_correction.xml',
        'views/payroll_premi.xml',
        'views/payroll_master_config.xml',
        'views/attendance_master_config.xml',
        'views/attendance_attendance.xml',
        'views/attendance_lupa.xml',
        'views/recruitment_fpk.xml',
        'views/recruitment_application.xml',
        'views/recruitment_report_config.xml',
        'views/timeoff_mytimeoff_overview.xml',
        'views/timeoff_approvals_timeoff.xml',
        'views/timeoff_approvals_allocations.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'auto_install': False,
    'qweb': [
        # "static/src/xml/attendance.xml",
    ],
    'application': False,
}
