from . import salary_correction
from . import hr_salary_rule
from . import hr_premi
from . import hr_contract
from . import hr_payslip
from . import hr_payroll_structure
from . import master_umk
from . import hr_leave_type
from . import hr_job