from . import hr_department
from . import hr_attendance
from . import dym_teguran_attendance
from . import hr_employee
from . import hr_grade_jabatan
from . import hr_resume
from . import hr_employee_type
from . import hr_surat_teguran
from . import hr_kompensasi_pkwt
from . import hr_work_location
from . import hr_contract
from . import form_lupa_absen
from . import hr_promosi_demosi_mutasi
from . import matrix_approval
from . import hr_terminasi
from . import hr_payslip
from . import resource_calendar